name: Lint

on: [push, pull_request]

jobs:
    build:
        runs-on: macOS-latest

        steps:
            - uses: actions/checkout@v1
            - name: Install
              run: brew install swiftlint
            - name: Lint
              run: cd Crypto && swiftlint lint --reporter junit
